name: custom-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - nltk
  - scikit-learn
  - pip
  - pip:
      - langdetect
      - mlflow==2.8.1
      - azureml-mlflow