name: custom-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - scikit-learn
  - pandas
  - numpy
  - pip:
      - mlflow
      - argparse
      - langdetect
      - nltk
build:
  script: ./post_build.sh